/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as CategoriasCategoriaRouteImport } from './routes/categorias.$categoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasCategoriaRoute = CategoriasCategoriaRouteImport.update({
  id: '/categorias/$categoria',
  path: '/categorias/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/categorias/': typeof CategoriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/categorias': typeof CategoriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/categorias/': typeof CategoriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/usuarios' | '/categorias/$categoria' | '/categorias/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/usuarios' | '/categorias/$categoria' | '/categorias'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/usuarios'
    | '/categorias/$categoria'
    | '/categorias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UsuariosRoute: typeof UsuariosRoute
  CategoriasCategoriaRoute: typeof CategoriasCategoriaRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$categoria': {
      id: '/categorias/$categoria'
      path: '/categorias/$categoria'
      fullPath: '/categorias/$categoria'
      preLoaderRoute: typeof CategoriasCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UsuariosRoute: UsuariosRoute,
  CategoriasCategoriaRoute: CategoriasCategoriaRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
